# Generated by OrchestKit Claude Plugin
# Created: 2026-07-26

"""Seed structural edge-case fixtures for the v4.1 audit (AUD-04 / D-122-11..13).

Additive on top of `seed_demo_data` -- NEVER a replacement. Injects edges a
clean demo seed structurally cannot contain: nullable fields actually NULL,
entities with genuinely empty history, enough rows to force pagination past
page 1, money boundaries (zero / negative-refund / very large kopecks), and
an Europe/Moscow UTC-vs-local day-rollover boundary (D-122-12). See
`.planning/audits/v4.1-EDGE-SEED-MATRIX.md` for the coverage grid this
script implements.

Re-running the clean demo seed alone is explicitly NOT AUD-04 evidence
(D-122-12) -- this script IS the evidence; 122-05's live-backend hunt runs
against the dataset produced here, never a fresh reseed.

Idempotent: every row keyed by a deterministic uuid5 id (NAMESPACE_DNS over
an `edge_*@fixture.local` string, mirroring seed_verification_fixtures.py)
via ON CONFLICT (id) DO NOTHING. Re-running after fixtures exist is a no-op.

Requires `seed_demo_data` to have run first (owner + >=1 active
MembershipPlan). One-shot, docker-compose only (D-122-13, never k3d/prod):

    cd apps/backend && uv run python -m scripts.seed_edge_cases

Guard mirrors seed_verification_fixtures TM-29-02 (T-122-05 mitigation).
"""

from __future__ import annotations

import asyncio
import sys
import uuid
from datetime import datetime
from zoneinfo import ZoneInfo

from sqlalchemy import select
from sqlalchemy.dialects.postgresql import insert as pg_insert
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine

from app.core.config import get_settings
from app.core.permissions import Role
from app.modules.auth.models import User
from app.modules.clients.models import Client
from app.modules.memberships.models import Membership, MembershipPlan
from app.modules.messaging.models import MessageThread
from app.modules.payments.models import Payment
from app.modules.trainers.models import Trainer
from app.modules.visits.models import Visit

_NS = uuid.NAMESPACE_DNS
_MSK = ZoneInfo("Europe/Moscow")
_REFUND_KOPECKS = 500_000  # 5 000 RUB -- negative/refund boundary
_LARGE_KOPECKS = 999_999_999_00  # ~9 999 999.99 RUB -- BigInteger boundary
_PAGINATION_COUNT = 30  # forces /clients page 2+ regardless of demo volume


def _uid(key: str) -> uuid.UUID:
    return uuid.uuid5(_NS, key)


async def _upsert(session: AsyncSession, model: type, **values: object) -> None:
    """ON CONFLICT (id) DO NOTHING -- deterministic-id idempotency (D-122-11)."""
    stmt = pg_insert(model).values(**values).on_conflict_do_nothing(index_elements=["id"])
    await session.execute(stmt)


async def _get_owner(session: AsyncSession) -> User:
    owner = await session.scalar(
        select(User).where(User.role == Role.OWNER).order_by(User.created_at)
    )
    if owner is None:
        print("ERROR: run `uv run python -m scripts.seed_demo_data` first.", file=sys.stderr)
        raise SystemExit(1)
    return owner


async def _get_base_plan(session: AsyncSession) -> MembershipPlan:
    plan = await session.scalar(
        select(MembershipPlan)
        .where(MembershipPlan.active.is_(True))
        .where(MembershipPlan.deleted_at.is_(None))
        .order_by(MembershipPlan.created_at)
    )
    if plan is None:
        print("ERROR: no active MembershipPlan. Run seed_demo_data first.", file=sys.stderr)
        raise SystemExit(1)
    return plan


async def _seed_null_and_empty_history(session: AsyncSession, owner: User) -> None:
    """Axis 1 (nullable actually NULL) + axis 2 (empty history)."""
    await _upsert(
        session,
        Client,
        id=_uid("edge_null_fields@fixture.local"),
        last_name="EdgeNullFields",
        first_name="Client",
        phone="+79001009001",
        created_by_user_id=owner.id,
    )  # every nullable column left unset -> NULL
    await _upsert(
        session,
        Client,
        id=_uid("edge_empty_history@fixture.local"),
        last_name="EdgeEmptyHistory",
        first_name="Client",
        phone="+79001009002",
        email="edge_empty_history@fixture.local",
        created_by_user_id=owner.id,
    )  # zero visits/bookings/memberships -- absence IS the fixture
    await _upsert(
        session,
        Trainer,
        id=_uid("edge_null_fields_trainer@fixture.local"),
        full_name="Edge NullFields Trainer",
    )  # phone/bio/specialization/photo_url all NULL
    await _upsert(
        session,
        Trainer,
        id=_uid("edge_empty_history_trainer@fixture.local"),
        full_name="Edge EmptyHistory Trainer",
        phone="+79003000001",
        specialization="Общая физическая подготовка",
        is_active=True,
    )  # zero bookings -- no availability slot ever created
    print("Seeded null-fields + empty-history client/trainer fixtures.")


async def _seed_pagination_clients(session: AsyncSession, owner: User) -> None:
    """Axis 3 -- enough rows to force /clients pagination past page 1."""
    for n in range(1, _PAGINATION_COUNT + 1):
        await _upsert(
            session,
            Client,
            id=_uid(f"edge_pagination_client_{n:03d}@fixture.local"),
            last_name="EdgePagination",
            first_name=f"Client{n:03d}",
            phone=f"+7900200{n:04d}",
            created_by_user_id=owner.id,
        )
    print(f"Seeded {_PAGINATION_COUNT} pagination clients (idempotent).")


async def _seed_money_boundaries(session: AsyncSession, owner: User, plan: MembershipPlan) -> None:
    """Axis 5 -- zero / negative-refund / very-large kopeck boundaries.

    Payment.amount_kopecks CHECKs forbid literal zero (must be >0 or <0
    depending on subject_kind), so zero is injected one layer up as a
    free/comped MembershipPlan instead.
    """
    today = datetime.now(_MSK).date()

    await _upsert(
        session,
        MembershipPlan,
        id=_uid("edge_zero_price_plan@fixture.local"),
        name="Edge: бесплатный (0 RUB)",
        duration_days=30,
        price_kopecks=0,
        freeze_days_limit=0,
        active=True,
    )

    money_client_id = _uid("edge_money_client@fixture.local")
    await _upsert(
        session,
        Client,
        id=money_client_id,
        last_name="EdgeMoney",
        first_name="Refund",
        phone="+79001009003",
        email="edge_money_client@fixture.local",
        created_by_user_id=owner.id,
    )
    money_membership_id = _uid("edge_money_membership@fixture.local")
    await _upsert(
        session,
        Membership,
        id=money_membership_id,
        client_id=money_client_id,
        plan_id=plan.id,
        plan_name_snapshot=plan.name,
        duration_days_snapshot=plan.duration_days,
        price_kopecks_snapshot=_REFUND_KOPECKS,
        freeze_days_limit_snapshot=plan.freeze_days_limit,
        start_date=today,
        end_date=today,
        status="cancelled",
        cancellation_reason="edge-case: refunded fixture (D-122-12 money axis)",
    )
    original_payment_id = _uid("edge_money_payment_original@fixture.local")
    await _upsert(
        session,
        Payment,
        id=original_payment_id,
        subject_kind="membership",
        subject_id=money_membership_id,
        amount_kopecks=_REFUND_KOPECKS,
        method="cash",
        received_by_user_id=owner.id,
    )
    await _upsert(
        session,
        Payment,
        id=_uid("edge_money_payment_refund@fixture.local"),
        subject_kind="refund",
        subject_id=money_membership_id,
        amount_kopecks=-_REFUND_KOPECKS,
        method="cash",
        received_by_user_id=owner.id,
        refund_of=original_payment_id,
    )

    large_client_id = _uid("edge_large_money_client@fixture.local")
    await _upsert(
        session,
        Client,
        id=large_client_id,
        last_name="EdgeMoney",
        first_name="Large",
        phone="+79001009004",
        email="edge_large_money_client@fixture.local",
        created_by_user_id=owner.id,
    )
    large_membership_id = _uid("edge_large_money_membership@fixture.local")
    await _upsert(
        session,
        Membership,
        id=large_membership_id,
        client_id=large_client_id,
        plan_id=plan.id,
        plan_name_snapshot=plan.name,
        duration_days_snapshot=plan.duration_days,
        price_kopecks_snapshot=_LARGE_KOPECKS,
        freeze_days_limit_snapshot=plan.freeze_days_limit,
        start_date=today,
        end_date=today,
        status="active",
    )
    await _upsert(
        session,
        Payment,
        id=_uid("edge_large_money_payment@fixture.local"),
        subject_kind="membership",
        subject_id=large_membership_id,
        amount_kopecks=_LARGE_KOPECKS,
        method="card",
        received_by_user_id=owner.id,
    )
    print("Seeded money-boundary fixtures: zero-price plan, refund pair, large payment.")


async def _seed_dst_tz_boundary(session: AsyncSession, owner: User, plan: MembershipPlan) -> None:
    """Axis 6 -- Europe/Moscow UTC-vs-local day-rollover boundary.

    Russia abolished DST in 2011 (permanent MSK, UTC+3 -- no literal
    spring-forward/fall-back gap exists). The real TZ risk here is the
    UTC-vs-MSK calendar-day rollover: 00:30 MSK on 2026-01-01 is
    2025-12-31T21:30:00Z -- code deriving "today" via UTC instead of the
    Europe/Moscow local date would misfile this visit under the wrong day.
    """
    dst_client_id = _uid("edge_dst_client@fixture.local")
    await _upsert(
        session,
        Client,
        id=dst_client_id,
        last_name="EdgeDstTz",
        first_name="Client",
        phone="+79001009005",
        email="edge_dst_client@fixture.local",
        created_by_user_id=owner.id,
    )
    dst_membership_id = _uid("edge_dst_membership@fixture.local")
    checked_in_at = datetime(2026, 1, 1, 0, 30, tzinfo=_MSK)
    gym_date = checked_in_at.date()  # 2026-01-01 MSK; UTC instant is 2025-12-31T21:30:00Z
    await _upsert(
        session,
        Membership,
        id=dst_membership_id,
        client_id=dst_client_id,
        plan_id=plan.id,
        plan_name_snapshot=plan.name,
        duration_days_snapshot=plan.duration_days,
        price_kopecks_snapshot=plan.price_kopecks,
        freeze_days_limit_snapshot=plan.freeze_days_limit,
        start_date=datetime(2025, 12, 1, tzinfo=_MSK).date(),
        end_date=datetime(2026, 1, 31, tzinfo=_MSK).date(),
        status="active",
    )
    await _upsert(
        session,
        Visit,
        id=_uid("edge_dst_visit@fixture.local"),
        client_id=dst_client_id,
        membership_id=dst_membership_id,
        checked_in_at=checked_in_at,
        gym_date=gym_date,
        channel="reception",
        checked_in_by=owner.id,
    )
    print("Seeded Europe/Moscow UTC-vs-local day-rollover boundary visit.")


async def _seed_empty_chat_thread(session: AsyncSession, owner: User) -> None:
    """Axis 2 -- a chat thread that exists with zero messages under it."""
    chat_client_id = _uid("edge_chat_client@fixture.local")
    await _upsert(
        session,
        Client,
        id=chat_client_id,
        last_name="EdgeEmptyChat",
        first_name="Client",
        phone="+79001009006",
        email="edge_chat_client@fixture.local",
        created_by_user_id=owner.id,
    )
    await _upsert(
        session,
        MessageThread,
        id=_uid("edge_empty_thread@fixture.local"),
        client_id=chat_client_id,
        last_message_at=None,
        client_unread_count=0,
        staff_last_read_at=None,
    )
    print("Seeded empty chat thread (zero messages).")


async def _run() -> int:
    settings = get_settings()
    db_url = str(settings.database_url)
    if "localhost" not in db_url and "postgres:5432" not in db_url:
        # D-122-13 / T-122-05: docker-compose only, never k3d/staging/prod.
        print("ERROR: refuses to run against non-local DATABASE_URL (D-122-13).", file=sys.stderr)
        return 1

    engine = create_async_engine(db_url)
    sessionmaker = async_sessionmaker(engine, expire_on_commit=False)
    try:
        async with sessionmaker() as session:
            owner = await _get_owner(session)
            plan = await _get_base_plan(session)
            await _seed_null_and_empty_history(session, owner)
            await _seed_pagination_clients(session, owner)
            await _seed_money_boundaries(session, owner, plan)
            await _seed_dst_tz_boundary(session, owner, plan)
            await _seed_empty_chat_thread(session, owner)
            await session.commit()
            print("Edge-case seed complete (additive, idempotent). See v4.1-EDGE-SEED-MATRIX.md.")
    finally:
        await engine.dispose()
    return 0


def main() -> int:
    return asyncio.run(_run())


if __name__ == "__main__":
    raise SystemExit(main())
