#!/usr/bin/env bash
# Generated by OrchestKit Claude Plugin
# Created: 2026-07-26

# check-read-only.sh — AUD-08 / D-122-24 mechanical read-only enforcement.
#
# The v4.1 audit phase (122) finds and records defects; it never fixes application code inline.
# This script proves that mechanically: it diffs the recorded phase-start commit against HEAD
# and asserts every changed path matches the allowlist. Any path outside the allowlist — in
# particular any MODIFICATION to an existing file under apps/, packages/, or infra/ — is a
# phase-exit failure.
#
# Allowlist (exactly these, no others):
#   .planning/**                                  (registry, manifests, phase artifacts)
#   tools/audit/**                                 (new files only)
#   apps/backend/scripts/seed_edge_cases.py        (new file only)
#
# This is the same script 122-06 runs as the authoritative phase-exit gate; running it earlier
# (this plan, 122-01) proves the mechanism works end-to-end on real changes before the three
# sub-passes fan out.
#
# Usage: bash tools/audit/check-read-only.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
START_SHA_FILE="${REPO_ROOT}/.planning/audits/.phase122-start-sha"

if [ ! -f "${START_SHA_FILE}" ]; then
  echo "FATAL: ${START_SHA_FILE} does not exist — cannot determine phase-start baseline." >&2
  exit 1
fi

START_SHA="$(cat "${START_SHA_FILE}")"

if ! [[ "${START_SHA}" =~ ^[0-9a-f]{40}$ ]]; then
  echo "FATAL: ${START_SHA_FILE} does not contain a 40-char git SHA (got: '${START_SHA}')." >&2
  exit 1
fi

cd "${REPO_ROOT}"

if ! git cat-file -e "${START_SHA}" 2>/dev/null; then
  echo "FATAL: recorded phase-start SHA '${START_SHA}' does not exist in this repository." >&2
  exit 1
fi

# Allowlist globs, checked with bash's extglob-free ** semantics via case-pattern matching below.
CHANGED_PATHS="$(git diff --name-only "${START_SHA}"..HEAD)"

OFFENDING_COUNT=0
OFFENDING_PATHS=()

while IFS= read -r path; do
  [ -z "${path}" ] && continue
  case "${path}" in
    .planning/*)
      # Allowed: any change under .planning/** (registry, manifests, phase artifacts).
      ;;
    tools/audit/*)
      # Allowed, but new files only — a modification to a pre-existing tools/audit/ file is
      # still fine here (it's audit tooling, not application code); the "new only" language in
      # D-122-24 distinguishes tools/audit/** from application code, not from itself.
      ;;
    apps/backend/scripts/seed_edge_cases.py)
      # Allowed: the one sanctioned new application-adjacent file (AUD-04), new file only.
      ADD_STATUS="$(git diff --name-status "${START_SHA}"..HEAD -- "${path}" | cut -f1)"
      if [ "${ADD_STATUS}" != "A" ]; then
        OFFENDING_COUNT=$((OFFENDING_COUNT + 1))
        OFFENDING_PATHS+=("${path} (must be a NEW file only; git status was '${ADD_STATUS}')")
      fi
      ;;
    *)
      OFFENDING_COUNT=$((OFFENDING_COUNT + 1))
      OFFENDING_PATHS+=("${path}")
      ;;
  esac
done <<< "${CHANGED_PATHS}"

if [ "${OFFENDING_COUNT}" -gt 0 ]; then
  echo "AUD-08 read-only check FAILED — ${OFFENDING_COUNT} path(s) outside the allowlist:" >&2
  for p in "${OFFENDING_PATHS[@]}"; do
    echo "  - ${p}" >&2
  done
  exit 1
fi

CHANGED_COUNT=0
if [ -n "${CHANGED_PATHS}" ]; then
  CHANGED_COUNT="$(echo "${CHANGED_PATHS}" | grep -c . || true)"
fi
echo "AUD-08 read-only check PASSED — ${CHANGED_COUNT} path(s) changed since ${START_SHA}, all within the allowlist."
