/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate email+password; issue cookies + envelope (AUTH-EP-01..02, AUTH-EP-05).
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revoke current family + clear cookies (AUTH-LO-01).
         *
         *     Idempotent: if the refresh cookie is absent or already revoked, the cookie
         *     clear still runs so the browser ends in a clean state.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout All
         * @description Revoke ALL alive families for the user + clear caller's cookies (AUTH-LO-02).
         */
        post: operations["logout_all_api_v1_auth_logout_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Return the authenticated user's profile (AUTH-LO-04).
         *
         *     `CurrentUser` is a Protocol with `id` + `role` only. The route knows the
         *     runtime instance is the SA `User` model (registered via register_user_loader
         *     in app.main.create_app), so we cast for access to email / full_name /
         *     telegram_chat_id. The cast is safe because the loader is fixed at composition.
         */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Rotate the refresh token; reissue all three cookies (AUTH-05/06).
         *
         *     Reads `sz_refresh` cookie directly (NOT via the auth dep — an expired
         *     access token must NOT block a refresh call). The body is empty on
         *     success: the new tokens travel in cookies. CSRF dep is exempt (Phase 6
         *     CSRF-02 / D-09 list).
         */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/telegram/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Telegram Start
         * @description Mint a deep-link token (AUTH-TG-01).
         *
         *     Returns the deep-link URL the FE shows to the operator. The OtpCode row
         *     is created with code_hash=NULL — the bot will fill it after /start <token>.
         */
        post: operations["telegram_start_api_v1_auth_telegram_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/telegram/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Telegram Status
         * @description Poll: has the bot DMed the code yet? (AUTH-TG-03).
         *
         *     Per D-19: never raises; unknown / expired / consumed all return bound=False
         *     (do NOT leak token validity).
         */
        get: operations["telegram_status_api_v1_auth_telegram_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/telegram/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Telegram Verify
         * @description Verify the 6-digit OTP and issue session cookies (AUTH-TG-04, AUTH-TG-06).
         *
         *     On success: mints tokens + cookies identical to /login, then emits
         *     `login_success` with `channel='telegram'` (D-14). Distinct error codes
         *     per D-13 ride the AppError envelope handler. BotNotStarted is re-raised
         *     with `fields={'deepLinkUrl': ...}` so the FE can re-display the deep-link
         *     button (D-13 row 1).
         */
        post: operations["telegram_verify_api_v1_auth_telegram_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List alive clients with filters and pagination
         * @description List alive clients (CLIENTS-03/04). VIEW permission required (D-21).
         */
        get: operations["list_clients_api_v1_clients_get"];
        put?: never;
        /**
         * Create a new client (E.164 phone; 409 phone_exists on partial-unique conflict)
         * @description Create a client (CLIENTS-06). EDIT permission + CSRF required (D-21).
         */
        post: operations["create_client_api_v1_clients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/{client_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a single alive client by id (404 if soft-deleted or missing)
         * @description Read one alive client (CLIENTS-05). 404 for missing or soft-deleted ids.
         */
        get: operations["get_client_api_v1_clients__client_id__get"];
        put?: never;
        post?: never;
        /**
         * Soft-delete a client (owner-only; sets deleted_at, never hard-deletes)
         * @description Soft-delete an alive client (CLIENTS-08).
         *
         *     Owner-only: (DELETE, CLIENTS) is in OWNER_ONLY, so reception → 403 from
         *     require_permission. CSRF required on the mutation. Returns 204 No Content;
         *     FastAPI emits an empty body for 204 status_code.
         */
        delete: operations["soft_delete_client_api_v1_clients__client_id__delete"];
        options?: never;
        head?: never;
        /**
         * Partial update (PATCH semantics; null-out via PATCH not supported in v1.1)
         * @description Partial update of an alive client (CLIENTS-07). EDIT + CSRF (D-21).
         */
        patch: operations["update_client_api_v1_clients__client_id__patch"];
        trace?: never;
    };
    "/api/v1/membership-plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List alive membership plans (owner-only); paginated; ?active filter
         * @description List alive membership plans (MEM-PLAN-EP-01). VIEW permission required.
         */
        get: operations["list_plans_api_v1_membership_plans_get"];
        put?: never;
        /**
         * Create a membership plan (owner-only; 409 plan_name_exists on duplicate alive name)
         * @description Create a membership plan (MEM-PLAN-EP-02). CREATE permission + CSRF required.
         */
        post: operations["create_plan_api_v1_membership_plans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/membership-plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch a single alive membership plan (owner-only)
         * @description Read one alive membership plan. 404 for missing or soft-deleted ids.
         */
        get: operations["get_plan_api_v1_membership_plans__plan_id__get"];
        put?: never;
        post?: never;
        /**
         * Soft-delete a membership plan (owner-only); frees lower(name) unique slot
         * @description Soft-delete an alive membership plan (MEM-PLAN-EP-04).
         *
         *     Owner-only: (DELETE, MEMBERSHIP_PLANS) is in OWNER_ONLY, so reception → 403 from
         *     require_permission. CSRF required on the mutation. Returns 204 No Content.
         *
         *     D-15: Phase 16 ships soft-delete only — no 409 plan_in_use. The memberships table
         *     FK plan_id ON DELETE RESTRICT and _is_plan_in_use_conflict helper arrive in Phase 17.
         */
        delete: operations["soft_delete_plan_api_v1_membership_plans__plan_id__delete"];
        options?: never;
        head?: never;
        /**
         * Patch a membership plan (owner-only); durationDays is immutable (rejected with 422)
         * @description Partial update of an alive membership plan (MEM-PLAN-EP-03). EDIT + CSRF required.
         */
        patch: operations["update_plan_api_v1_membership_plans__plan_id__patch"];
        trace?: never;
    };
    "/api/v1/memberships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List memberships filtered by clientId/status with pagination
         * @description List memberships, paginated (MEM-EP-01).
         *
         *     Query parameters (Phase 17 D-09):
         *       - clientId — optional UUID filter; omit for global feed (owner)
         *       - status   — optional single-value enum (active|expired|cancelled); omit for all
         *       - sort     — created_at_desc (default) | end_date_desc | start_date_desc
         *       - page / pageSize — PageQuery contract (default 1 / 20, max 100)
         */
        get: operations["list_memberships_api_v1_memberships_get"];
        put?: never;
        /**
         * Sell a membership (reception+owner; 404 plan_not_found, 409 plan_inactive)
         * @description Sell a membership (MEM-EP-03). CREATE permission + CSRF required.
         *
         *     (CREATE, MEMBERSHIPS) is NOT in OWNER_ONLY — reception receives 201 on success.
         *     Service layer validates plan presence (404 plan_not_found) and active flag
         *     (409 plan_inactive) and computes start_date/end_date server-side (D-04).
         */
        post: operations["create_membership_api_v1_memberships_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memberships/{membership_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a membership by id (404 membership_not_found)
         * @description Read one membership (MEM-EP-02). 404 `membership_not_found` for missing ids.
         */
        get: operations["get_membership_api_v1_memberships__membership_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memberships/{membership_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a membership (owner-only; 409 invalid_transition for non-active source)
         * @description Cancel a membership (MEM-EP-04). Owner-only — reception → 403 from RBAC gate.
         *
         *     (CANCEL, MEMBERSHIPS) is in OWNER_ONLY (Phase 15 INFRA-08). CSRF required on
         *     the mutation. Returns 200 with the cancelled MembershipResponse (NOT 204 —
         *     the body carries the post-transition row including `cancelled_at`).
         *
         *     State machine (Phase 17 D-12): only `active → cancelled` is allowed; `expired`
         *     and `cancelled` source states raise 409 `invalid_transition` with payload
         *     `{from_status, to_status}`.
         */
        post: operations["cancel_membership_api_v1_memberships__membership_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/visits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List visits filtered by clientId/from/to with pagination
         * @description List visits, paginated (VIS-EP-01). VIEW permission required.
         */
        get: operations["list_visits_api_v1_visits_get"];
        put?: never;
        /**
         * Reception manual check-in (reception+owner; 409 outside_gym_hours / no_active_membership / duplicate_checkin)
         * @description Reception manual check-in (VIS-EP-03). CHECK_IN permission + CSRF required.
         *
         *     Sealed body — only `clientId` accepted (D-01). Every other field is
         *     server-derived: membershipId resolved via resolve_active_membership;
         *     checkedInAt defaults to DB now(); gymDate is the STORED GENERATED column;
         *     channel is 'reception'; checkedInBy is actor.id.
         *
         *     RBAC-04: `actor` (require_permission) parameter is declared BEFORE
         *     `_csrf` (verify_csrf) so unauthenticated callers see 401, not CSRF
         *     errors. (CHECK_IN, VISITS) is NOT in OWNER_ONLY — reception receives
         *     201 on success.
         */
        post: operations["create_visit_api_v1_visits_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/visits/{visit_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a single visit by id (404 visit_not_found)
         * @description Read one visit (VIS-EP-02). 404 `visit_not_found` for missing ids.
         */
        get: operations["get_visit_api_v1_visits__visit_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe. Returns {"status": "ok"} with HTTP 200.
         */
        get: operations["health_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ClientCreateRequest
         * @description POST /api/v1/clients body. Required: lastName, firstName, phone.
         */
        ClientCreateRequest: {
            /** Birthday */
            birthday?: string | null;
            /** Email */
            email?: string | null;
            emergencyContact?: components["schemas"]["EmergencyContact"] | null;
            /** Firstname */
            firstName: string;
            gender?: components["schemas"]["Gender"] | null;
            /** Lastname */
            lastName: string;
            /** Middlename */
            middleName?: string | null;
            /** Notes */
            notes?: string | null;
            /** Phone */
            phone: string;
            /** Tags */
            tags?: string[];
            /** Telegramuserid */
            telegramUserId?: number | null;
        };
        /**
         * ClientResponse
         * @description Single client read DTO. `from_attributes=True` (inherited via ContractModel)
         *     allows `ClientResponse.model_validate(orm_client_instance)`.
         *
         *     `deleted_at` is intentionally omitted — soft-deleted rows are 404'd at the
         *     repository boundary (Plan 04 `get_alive`); the response shape never carries it.
         */
        ClientResponse: {
            /** Birthday */
            birthday?: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Createdbyuserid
             * Format: uuid
             */
            createdByUserId: string;
            /** Email */
            email?: string | null;
            emergencyContact?: components["schemas"]["EmergencyContact"] | null;
            /** Firstname */
            firstName: string;
            gender?: components["schemas"]["Gender"] | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Lastname */
            lastName: string;
            /** Middlename */
            middleName?: string | null;
            /** Notes */
            notes?: string | null;
            /** Phone */
            phone: string;
            /** Tags */
            tags: string[];
            /** Telegramuserid */
            telegramUserId?: number | null;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /**
         * ClientSort
         * @description Client list sort modes (CLIENTS-04).
         * @enum {string}
         */
        ClientSort: "created_at_desc" | "last_name_asc";
        /**
         * ClientUpdateRequest
         * @description PATCH /api/v1/clients/{id} body.
         *
         *     Semantics: caller sends only the fields they want to change; service does
         *     `model_dump(exclude_unset=True)` and applies that subset. D-01 forbids explicit
         *     null in v1.1 — to leave a field unchanged, OMIT the key entirely.
         */
        ClientUpdateRequest: {
            /** Birthday */
            birthday?: string | null;
            /** Email */
            email?: string | null;
            emergencyContact?: components["schemas"]["EmergencyContact"] | null;
            /** Firstname */
            firstName?: string | null;
            gender?: components["schemas"]["Gender"] | null;
            /** Lastname */
            lastName?: string | null;
            /** Middlename */
            middleName?: string | null;
            /** Notes */
            notes?: string | null;
            /** Phone */
            phone?: string | null;
            /** Tags */
            tags?: string[] | null;
            /** Telegramuserid */
            telegramUserId?: number | null;
        };
        /**
         * EmergencyContact
         * @description Free-shape contact owned by UI (D-17). Same E.164 phone as Client.phone.
         */
        EmergencyContact: {
            /** Name */
            name: string;
            /** Phone */
            phone: string;
            /** Relation */
            relation?: string | null;
        };
        /**
         * Gender
         * @description Client gender (D-15). Closed enum — only male/female v1.
         * @enum {string}
         */
        Gender: "male" | "female";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LoginRequest
         * @description POST /api/v1/auth/login body.
         */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * LoginResponse
         * @description POST /api/v1/auth/login response body (wrapped in ResponseEnvelope).
         */
        LoginResponse: {
            user: components["schemas"]["UserPublic"];
        };
        /**
         * MeResponse
         * @description GET /api/v1/auth/me response body (wrapped in ResponseEnvelope).
         */
        MeResponse: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Fullname */
            fullName: string;
            /** Hastelegram */
            hasTelegram: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            role: components["schemas"]["Role"];
        };
        /**
         * MembershipCancelRequest
         * @description POST /api/v1/memberships/{id}/cancel body (Phase 17 D-11).
         *
         *     Reason is optional (matches MEM-AUDIT-01 — `reason?` in audit payload).
         *     Max length 500 — half the notes ceiling: a cancellation reason is a short
         *     operator note, not a free-form essay (T-17-01 mitigation).
         *
         *     Explicit-null guard ported VERBATIM from Phase 16 D-05 (T-PYDANTIC-NULL).
         */
        MembershipCancelRequest: {
            /** Reason */
            reason?: string | null;
        };
        /**
         * MembershipCreateRequest
         * @description POST /api/v1/memberships body (Phase 17 D-03).
         *
         *     start_date / end_date / status / activation_policy are server-computed
         *     (D-04) and intentionally absent — the inherited extra='forbid' will reject
         *     any payload that includes them.
         */
        MembershipCreateRequest: {
            /**
             * Clientid
             * Format: uuid
             */
            clientId: string;
            /** Notes */
            notes?: string | null;
            /** Paidat */
            paidAt?: string | null;
            /**
             * Planid
             * Format: uuid
             */
            planId: string;
        };
        /**
         * MembershipListSort
         * @description Membership list sort modes (Phase 17 D-09).
         * @enum {string}
         */
        MembershipListSort: "created_at_desc" | "end_date_desc" | "start_date_desc";
        /**
         * MembershipPlanCreateRequest
         * @description POST /api/v1/membership-plans body.
         */
        MembershipPlanCreateRequest: {
            /**
             * Active
             * @default true
             */
            active: boolean;
            /** Durationdays */
            durationDays: number;
            /** Name */
            name: string;
            /** Pricekopecks */
            priceKopecks: number;
        };
        /**
         * MembershipPlanResponse
         * @description Outbound representation of a MembershipPlan.
         */
        MembershipPlanResponse: {
            /** Active */
            active: boolean;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Durationdays */
            durationDays: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Pricekopecks */
            priceKopecks: number;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /**
         * MembershipPlanSort
         * @description Membership plan list sort modes (D-08, CD-04).
         * @enum {string}
         */
        MembershipPlanSort: "created_at_desc" | "name_asc";
        /**
         * MembershipPlanUpdateRequest
         * @description PATCH /api/v1/membership-plans/{id} body.
         *
         *     D-04: duration_days is intentionally absent — extra='forbid' (inherited
         *     from BackendSchemaBase) raises stock 422 if a payload contains
         *     `durationDays` (or `duration_days`). The rejected key is named in the
         *     Pydantic error response.
         */
        MembershipPlanUpdateRequest: {
            /** Active */
            active?: boolean | null;
            /** Name */
            name?: string | null;
            /** Pricekopecks */
            priceKopecks?: number | null;
        };
        /**
         * MembershipResponse
         * @description Outbound representation of a Membership (Phase 17 D-10).
         *
         *     Exposes ALL snapshot fields so the frontend (Phase 22) can render
         *     historical sales correctly even after the source plan is edited or
         *     deleted.
         */
        MembershipResponse: {
            /** Cancelreason */
            cancelReason: string | null;
            /** Cancelledat */
            cancelledAt: string | null;
            /**
             * Clientid
             * Format: uuid
             */
            clientId: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Durationdayssnapshot */
            durationDaysSnapshot: number;
            /**
             * Enddate
             * Format: date
             */
            endDate: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Notes */
            notes: string | null;
            /** Paidat */
            paidAt: string | null;
            /**
             * Planid
             * Format: uuid
             */
            planId: string;
            /** Plannamesnapshot */
            planNameSnapshot: string;
            /** Pricekopeckssnapshot */
            priceKopecksSnapshot: number;
            /**
             * Startdate
             * Format: date
             */
            startDate: string;
            status: components["schemas"]["MembershipStatus"];
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /**
         * MembershipStatus
         * @description Membership lifecycle status (CONTEXT.md domain line 12).
         * @enum {string}
         */
        MembershipStatus: "active" | "expired" | "cancelled";
        /** PaginatedData[ClientResponse] */
        PaginatedData_ClientResponse_: {
            /** Items */
            items: components["schemas"]["ClientResponse"][];
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
            /** Total */
            total: number;
        };
        /** PaginatedData[MembershipPlanResponse] */
        PaginatedData_MembershipPlanResponse_: {
            /** Items */
            items: components["schemas"]["MembershipPlanResponse"][];
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
            /** Total */
            total: number;
        };
        /** PaginatedData[MembershipResponse] */
        PaginatedData_MembershipResponse_: {
            /** Items */
            items: components["schemas"]["MembershipResponse"][];
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
            /** Total */
            total: number;
        };
        /** PaginatedData[VisitResponse] */
        PaginatedData_VisitResponse_: {
            /** Items */
            items: components["schemas"]["VisitResponse"][];
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
            /** Total */
            total: number;
        };
        /** ResponseEnvelope[ClientResponse] */
        ResponseEnvelope_ClientResponse_: {
            data: components["schemas"]["ClientResponse"];
        };
        /** ResponseEnvelope[LoginResponse] */
        ResponseEnvelope_LoginResponse_: {
            data: components["schemas"]["LoginResponse"];
        };
        /** ResponseEnvelope[MeResponse] */
        ResponseEnvelope_MeResponse_: {
            data: components["schemas"]["MeResponse"];
        };
        /** ResponseEnvelope[MembershipPlanResponse] */
        ResponseEnvelope_MembershipPlanResponse_: {
            data: components["schemas"]["MembershipPlanResponse"];
        };
        /** ResponseEnvelope[MembershipResponse] */
        ResponseEnvelope_MembershipResponse_: {
            data: components["schemas"]["MembershipResponse"];
        };
        /** ResponseEnvelope[NoneType] */
        ResponseEnvelope_NoneType_: {
            /** Data */
            data: null;
        };
        /** ResponseEnvelope[PaginatedData[ClientResponse]] */
        ResponseEnvelope_PaginatedData_ClientResponse__: {
            data: components["schemas"]["PaginatedData_ClientResponse_"];
        };
        /** ResponseEnvelope[PaginatedData[MembershipPlanResponse]] */
        ResponseEnvelope_PaginatedData_MembershipPlanResponse__: {
            data: components["schemas"]["PaginatedData_MembershipPlanResponse_"];
        };
        /** ResponseEnvelope[PaginatedData[MembershipResponse]] */
        ResponseEnvelope_PaginatedData_MembershipResponse__: {
            data: components["schemas"]["PaginatedData_MembershipResponse_"];
        };
        /** ResponseEnvelope[PaginatedData[VisitResponse]] */
        ResponseEnvelope_PaginatedData_VisitResponse__: {
            data: components["schemas"]["PaginatedData_VisitResponse_"];
        };
        /** ResponseEnvelope[TelegramStartResponse] */
        ResponseEnvelope_TelegramStartResponse_: {
            data: components["schemas"]["TelegramStartResponse"];
        };
        /** ResponseEnvelope[TelegramStatusResponse] */
        ResponseEnvelope_TelegramStatusResponse_: {
            data: components["schemas"]["TelegramStatusResponse"];
        };
        /** ResponseEnvelope[VisitResponse] */
        ResponseEnvelope_VisitResponse_: {
            data: components["schemas"]["VisitResponse"];
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "owner" | "reception";
        /**
         * TelegramStartResponse
         * @description POST /auth/telegram/start success body (AUTH-TG-01).
         *
         *     snake_case → camelCase auto: `deep_link_url` → `deepLinkUrl`,
         *     `deep_link_token` → `deepLinkToken`.
         */
        TelegramStartResponse: {
            /** Deeplinktoken */
            deepLinkToken: string;
            /** Deeplinkurl */
            deepLinkUrl: string;
        };
        /**
         * TelegramStatusResponse
         * @description GET /auth/telegram/status success body (AUTH-TG-03).
         */
        TelegramStatusResponse: {
            /** Bound */
            bound: boolean;
        };
        /**
         * TelegramVerifyRequest
         * @description POST /auth/telegram/verify request body (AUTH-TG-04).
         *
         *     `code` must be exactly 6 digits — short-circuits non-digit input
         *     before the service hits Postgres.
         */
        TelegramVerifyRequest: {
            /** Code */
            code: string;
            /** Deeplinktoken */
            deepLinkToken: string;
        };
        /**
         * UserPublic
         * @description Subset of User exposed on login response.
         */
        UserPublic: {
            /** Fullname */
            fullName: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            role: components["schemas"]["Role"];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VisitCreateRequest
         * @description POST /api/v1/visits body (Phase 19 D-01).
         *
         *     Only clientId is accepted; every other field is server-derived (see module
         *     docstring). The inherited extra='forbid' rejects payload tampering.
         */
        VisitCreateRequest: {
            /**
             * Clientid
             * Format: uuid
             */
            clientId: string;
        };
        /**
         * VisitResponse
         * @description GET / POST response shape (Phase 19 VIS-EP-01..03).
         *
         *     from_attributes=True allows model_validate(visit_orm) directly.
         *     extra='ignore' (via ContractModel base) is overridden here because
         *     we merge BackendSchemaBase.model_config with from_attributes.
         */
        VisitResponse: {
            /** Channel */
            channel: string;
            /**
             * Checkedinat
             * Format: date-time
             */
            checkedInAt: string;
            /** Checkedinby */
            checkedInBy: string | null;
            /**
             * Clientid
             * Format: uuid
             */
            clientId: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Gymdate
             * Format: date
             */
            gymDate: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Membershipid
             * Format: uuid
             */
            membershipId: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_LoginResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_NoneType_"];
                };
            };
        };
    };
    logout_all_api_v1_auth_logout_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_NoneType_"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_MeResponse_"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_NoneType_"];
                };
            };
        };
    };
    telegram_start_api_v1_auth_telegram_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_TelegramStartResponse_"];
                };
            };
        };
    };
    telegram_status_api_v1_auth_telegram_status_get: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_TelegramStatusResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    telegram_verify_api_v1_auth_telegram_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelegramVerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_LoginResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_clients_api_v1_clients_get: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                q?: string | null;
                tag?: string | null;
                gender?: components["schemas"]["Gender"] | null;
                createdFrom?: string | null;
                createdTo?: string | null;
                hasTelegram?: boolean | null;
                sort?: components["schemas"]["ClientSort"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_PaginatedData_ClientResponse__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_client_api_v1_clients_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_ClientResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_client_api_v1_clients__client_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_ClientResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    soft_delete_client_api_v1_clients__client_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_client_api_v1_clients__client_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_ClientResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_plans_api_v1_membership_plans_get: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                active?: boolean | null;
                sort?: components["schemas"]["MembershipPlanSort"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_PaginatedData_MembershipPlanResponse__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_plan_api_v1_membership_plans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MembershipPlanCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_MembershipPlanResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plan_api_v1_membership_plans__plan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_MembershipPlanResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    soft_delete_plan_api_v1_membership_plans__plan_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_plan_api_v1_membership_plans__plan_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MembershipPlanUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_MembershipPlanResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_memberships_api_v1_memberships_get: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                clientId?: string | null;
                status?: components["schemas"]["MembershipStatus"] | null;
                sort?: components["schemas"]["MembershipListSort"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_PaginatedData_MembershipResponse__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_membership_api_v1_memberships_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MembershipCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_MembershipResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_membership_api_v1_memberships__membership_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                membership_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_MembershipResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_membership_api_v1_memberships__membership_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                membership_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MembershipCancelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_MembershipResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_visits_api_v1_visits_get: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                clientId?: string | null;
                from_?: string | null;
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_PaginatedData_VisitResponse__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_visit_api_v1_visits_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VisitCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_VisitResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_visit_api_v1_visits__visit_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                visit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_VisitResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
